name: Scheduled API Health Check

on:
  schedule:
    # Executa a cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  health-check:
    name: API Health Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run health check tests
        run: npm run test:ci
        continue-on-error: true
      
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: health-check-${{ github.run_number }}
          path: reports/
          retention-days: 7
      
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue_title = '🚨 API Health Check Failed';
            const issue_body = `
            ## Health Check Failure Report
            
            **Run ID**: ${{ github.run_id }}
            **Timestamp**: ${new Date().toISOString()}
            
            The scheduled health check has failed. Please investigate.
            
            [View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issue_title,
              body: issue_body,
              labels: ['bug', 'health-check']
            });
